"""Truss Structural Assessment 실패 진단 모듈 테스트.

배경: 200K_2TK_Rev2.bdf 는 Case Control 이
    DISPLACEMENT(PUNCH) = ALL
    ELFORCE(PRINT,PUNCH) = ALL
    SPCFORCES(PUNCH) = ALL
로 되어 있어 SPC 반력이 .f06 이 아닌 .pch 로만 출력된다.
엔진(TrussAssessment.exe)은 .f06 만 읽으므로 LoadDistributionChecker 에서
KeyNotFoundException('SPCForce') 로 죽고 exit code != 0 을 반환한다.
지금까지 백엔드/프론트가 엔진 출력을 버려서 화면에는 "해석 실패." 만 남았다.
"""
import pytest

from app.services.assessment_diagnostics import (
    build_failure_report,
    diagnose_engine_failure,
    preflight_case_control,
    read_case_control_head,
    redact_paths,
    scan_case_control,
)


# ── 실제 실패 파일과 동일한 Case Control ──────────────────────
FAILING_BDF = """\
$$ NASTRAN Input Deck Generated by HyperMesh
SOL 101
CEND
  DISPLACEMENT(PUNCH) = ALL
  ELFORCE(PRINT,PUNCH) = ALL
  SPCFORCES(PUNCH) = ALL
SUBCASE       1
  SPC =        1
  LOAD =        2
BEGIN BULK
GRID           1         44103.0 12920.0   770.0
FORCE          9       1       0     1.0     0.0     0.0  -100.0
ENDDATA
"""

# ── 참조 BDF(정상 동작)와 동일한 Case Control ─────────────────
PASSING_BDF = """\
SOL 101
CEND
  DISPLACEMENT(PRINT,PUNCH) = ALL
  ELFORCE(PRINT,PUNCH) = ALL
  SPCFORCES(PRINT,PUNCH) = ALL
SUBCASE       1
  SPC =        1
  LOAD =       10
BEGIN BULK
GRID           1         44103.0 12920.0   770.0
ENDDATA
"""


# ══════════════════════════════════════════════════════════════
# scan_case_control — Case Control 구간 파싱
# ══════════════════════════════════════════════════════════════
class TestScanCaseControl:
    def test_punch_only_does_not_print_to_f06(self):
        found = scan_case_control(FAILING_BDF)
        spc = found["SPCFORCES"][0]
        assert spc.describers == ("PUNCH",)
        assert spc.prints_to_f06 is False

    def test_print_punch_prints_to_f06(self):
        found = scan_case_control(FAILING_BDF)
        assert found["ELFORCE"][0].prints_to_f06 is True

    def test_no_describer_defaults_to_print(self):
        """NASTRAN 기본 describer 는 PRINT 이므로 괄호가 없으면 F06 에 출력된다."""
        found = scan_case_control("SOL 101\nCEND\n  ELFORCE = ALL\nBEGIN BULK\nENDDATA\n")
        assert found["ELFORCE"][0].prints_to_f06 is True

    def test_plot_only_does_not_print(self):
        found = scan_case_control("SOL 101\nCEND\n  ELFORCE(PLOT) = ALL\nBEGIN BULK\nENDDATA\n")
        assert found["ELFORCE"][0].prints_to_f06 is False

    @pytest.mark.parametrize("alias,canonical", [
        ("DISP", "DISPLACEMENT"),
        ("SPCF", "SPCFORCES"),
        ("FORCE", "ELFORCE"),
        ("ELFORCE", "ELFORCE"),
    ])
    def test_aliases_normalized(self, alias, canonical):
        text = f"SOL 101\nCEND\n  {alias}(PRINT) = ALL\nBEGIN BULK\nENDDATA\n"
        assert canonical in scan_case_control(text)

    def test_bulk_data_force_card_is_not_case_control(self):
        """BULK DATA 의 FORCE 하중 카드를 ELFORCE 출력 요청으로 오인하면 안 된다."""
        found = scan_case_control(FAILING_BDF)
        # Case Control 구간의 ELFORCE 1건만 잡혀야 한다 (BEGIN BULK 뒤 FORCE 카드 제외).
        assert len(found["ELFORCE"]) == 1

    def test_raw_line_preserved_for_user_message(self):
        found = scan_case_control(FAILING_BDF)
        assert "SPCFORCES(PUNCH) = ALL" in found["SPCFORCES"][0].raw


# ══════════════════════════════════════════════════════════════
# preflight_case_control — 엔진 실행 전 사전 검증
# ══════════════════════════════════════════════════════════════
class TestPreflightCaseControl:
    def test_failing_bdf_reports_spcforces_as_blocking(self):
        problems = preflight_case_control(FAILING_BDF)
        blocking = [p for p in problems if p.blocking]
        assert [p.command for p in blocking] == ["SPCFORCES"]

    def test_failing_bdf_message_names_current_and_required_form(self):
        problem = next(p for p in preflight_case_control(FAILING_BDF) if p.command == "SPCFORCES")
        assert "SPCFORCES(PUNCH) = ALL" in problem.current
        assert "SPCFORCES(PRINT,PUNCH) = ALL" in problem.required

    def test_displacement_punch_only_is_warning_not_blocking(self):
        """Displacement 는 검토 단계에서 소비되지 않으므로 경고로만 남긴다."""
        problem = next(p for p in preflight_case_control(FAILING_BDF) if p.command == "DISPLACEMENT")
        assert problem.blocking is False

    def test_passing_bdf_has_no_problems(self):
        assert preflight_case_control(PASSING_BDF) == []

    def test_missing_command_entirely_is_blocking(self):
        text = "SOL 101\nCEND\n  DISPLACEMENT(PRINT) = ALL\nBEGIN BULK\nENDDATA\n"
        blocking = {p.command for p in preflight_case_control(text) if p.blocking}
        assert blocking == {"ELFORCE", "SPCFORCES"}

    def test_print_in_any_occurrence_is_accepted(self):
        """전역 PUNCH + SUBCASE 별 PRINT 조합은 정상으로 본다(과잉 차단 방지)."""
        text = (
            "SOL 101\nCEND\n"
            "  DISPLACEMENT(PRINT) = ALL\n"
            "  ELFORCE(PUNCH) = ALL\n"
            "  SPCFORCES(PRINT,PUNCH) = ALL\n"
            "SUBCASE 1\n"
            "  ELFORCE(PRINT,PUNCH) = ALL\n"
            "BEGIN BULK\nENDDATA\n"
        )
        assert [p for p in preflight_case_control(text) if p.blocking] == []

    def test_no_cend_returns_no_problems(self):
        """Case Control 을 찾지 못하면 추측하지 않고 엔진 판단에 맡긴다."""
        assert preflight_case_control("GRID 1 0.0 0.0 0.0\n") == []


# ══════════════════════════════════════════════════════════════
# diagnose_engine_failure — 엔진 출력에서 실패 서명 인식
# ══════════════════════════════════════════════════════════════
class TestDiagnoseEngineFailure:
    REAL_OUTPUT = """\
[2026-07-30 14:35:47.757] [INFO ] BDF 파싱 완료 - GRID: 11472, CBAR: 15298, SUBCASE: 7
No displacement data found.
No SPC Force data found.
[2026-07-30 14:35:48.224] [WARN ] SPCForce 파싱 결과가 없습니다.
[2026-07-30 14:35:48.253] [INFO ] 부재 검토 완료 - 총 107086개 평가, Fail: 0개
[2026-07-30 14:35:48.253] [INFO ] 하중분산판 검토 수행 중...
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'SPCForce' was not present in the dictionary.
   at TrussAssessment.Control.LoadDistributionChecker.Run()
"""

    def test_recognizes_missing_spcforce(self):
        d = diagnose_engine_failure(self.REAL_OUTPUT)
        assert d is not None
        assert "SPCFORCES(PRINT,PUNCH)" in d.remedy
        assert "SPC 반력" in d.cause

    def test_recognizes_missing_elforce(self):
        d = diagnose_engine_failure(
            "No EL Force data found.\n"
            "Unhandled exception. System.Collections.Generic.KeyNotFoundException: "
            "The given key 'ELForce' was not present in the dictionary.\n"
        )
        assert "ELFORCE(PRINT,PUNCH)" in d.remedy

    def test_recognizes_f06_fatal(self):
        d = diagnose_engine_failure(
            "[FATAL] F06 FATAL 발견 (Line 812): *** USER FATAL MESSAGE 5423\n"
        )
        assert "FATAL" in d.cause
        assert d.stage == "Nastran 해석"

    def test_recognizes_missing_f06(self):
        d = diagnose_engine_failure("[ERROR] .f06 파일을 찾을 수 없습니다. Nastran 실행이 실패했을 수 있습니다.\n")
        assert "Nastran" in d.cause

    def test_recognizes_zero_element_evaluation(self):
        """104leg.bdf 사례 — Property ID 가 허용응력 테이블(1~18)과 어긋난 경우."""
        d = diagnose_engine_failure("[INFO ] 부재 검토 완료 - 총 0개 평가, Fail: 0개\n")
        assert "Property ID" in d.cause

    def test_recognizes_timeout(self):
        d = diagnose_engine_failure("해석 엔진이 제한 시간(600초)을 초과했습니다. 관리자에게 문의하세요.")
        assert "제한 시간" in d.cause

    def test_unknown_output_returns_none(self):
        assert diagnose_engine_failure("[INFO ] 모든 작업이 완료되었습니다.\n") is None

    def test_empty_output_returns_none(self):
        assert diagnose_engine_failure("") is None


# ══════════════════════════════════════════════════════════════
# read_case_control_head — BEGIN BULK 까지만 읽기
# ══════════════════════════════════════════════════════════════
class TestReadCaseControlHead:
    def test_stops_at_begin_bulk(self, tmp_path):
        bdf = tmp_path / "m.bdf"
        bdf.write_text(FAILING_BDF + "GRID 2\n" * 100_000, encoding="utf-8")
        head = read_case_control_head(str(bdf))
        assert "SPCFORCES(PUNCH)" in head
        assert head.count("GRID 2") <= 1  # BEGIN BULK 이후는 읽지 않는다

    def test_missing_file_returns_none(self, tmp_path):
        assert read_case_control_head(str(tmp_path / "nope.bdf")) is None

    def test_result_is_parseable_by_preflight(self, tmp_path):
        bdf = tmp_path / "m.bdf"
        bdf.write_text(FAILING_BDF, encoding="utf-8")
        problems = preflight_case_control(read_case_control_head(str(bdf)))
        assert [p.command for p in problems if p.blocking] == ["SPCFORCES"]


# ══════════════════════════════════════════════════════════════
# redact_paths — 서버 절대경로 비노출
# ══════════════════════════════════════════════════════════════
class TestRedactPaths:
    def test_work_dir_replaced_with_placeholder(self):
        work_dir = r"C:\KHM\HiTessWorkbench\userConnection\20260730_1_TrussAssessment"
        text = rf"BDF 파일: {work_dir}\200K.bdf"
        out = redact_paths(text, work_dir)
        assert work_dir not in out
        assert "200K.bdf" in out

    def test_case_insensitive_on_windows(self):
        work_dir = r"C:\KHM\userConnection\Job1"
        out = redact_paths(r"열기 실패: c:\khm\userconnection\job1\a.f06", work_dir)
        assert "c:\\khm" not in out.lower()

    def test_none_work_dir_is_safe(self):
        assert redact_paths("plain text", None) == "plain text"


# ══════════════════════════════════════════════════════════════
# build_failure_report — Execution Console 에 찍히는 최종 텍스트
# ══════════════════════════════════════════════════════════════
class TestBuildFailureReport:
    def test_report_contains_cause_and_remedy(self):
        d = diagnose_engine_failure(TestDiagnoseEngineFailure.REAL_OUTPUT)
        report = build_failure_report(
            diagnosis=d,
            engine_output=TestDiagnoseEngineFailure.REAL_OUTPUT,
            work_dir=None,
        )
        assert "[원인]" in report
        assert "[조치]" in report
        assert "SPCFORCES(PRINT,PUNCH)" in report

    def test_report_includes_engine_output_tail(self):
        report = build_failure_report(
            diagnosis=None,
            engine_output="line-A\nline-B\nUnhandled exception. Boom\n",
            work_dir=None,
        )
        assert "Unhandled exception. Boom" in report

    def test_report_without_diagnosis_still_shows_raw_output(self):
        report = build_failure_report(diagnosis=None, engine_output="무언가 이상함", work_dir=None)
        assert "무언가 이상함" in report

    def test_report_redacts_work_dir(self):
        work_dir = r"C:\KHM\userConnection\Job9"
        report = build_failure_report(
            diagnosis=None,
            engine_output=rf"파일 없음: {work_dir}\x.f06",
            work_dir=work_dir,
        )
        assert work_dir not in report

    def test_engine_output_is_tail_limited(self):
        huge = "\n".join(f"line{i}" for i in range(5000))
        report = build_failure_report(diagnosis=None, engine_output=huge, work_dir=None)
        assert len(report) < 20000
        assert "line4999" in report  # 마지막(가장 중요한) 줄은 반드시 남는다
