/**
 * @fileoverview Simple Beam Assessment 페이지 오케스트레이터 (BeamModelPreview)
 */
import React, { useState, useRef, useEffect } from 'react';
import { toPng } from 'html-to-image';
import { Box, Activity, Plus, Trash2, ShieldCheck, ArrowDown, RefreshCw, SlidersHorizontal, Play, FileJson, Upload, BarChart2, Camera, Info } from 'lucide-react';
import GuideButton from '../ui/GuideButton';
import { useBeamModeling } from '../../hooks/useBeamModeling';
import { useAnalysisManager } from '../../hooks/useAnalysisManager';
import { InputRow, SummaryRow, SectionGuide } from '../../components/analysis/BeamSharedUI';
import Viewer3D from '../../components/analysis/Viewer3D';
import EngineeringCharts from '../../components/analysis/EngineeringCharts';
import SolverCredit from '../ui/SolverCredit';
import { formatEngineering as engFormat } from '../../utils/formatting';

export default function BeamModelPreview() {
  const captureRef = useRef(null);
  const toastTimerRef = useRef(null);
  const captureTimerRef = useRef(null);
  const [activeTab, setActiveTab] = useState('modeling');
  const [isCapturing, setIsCapturing] = useState(false);
  const [toast, setToast] = useState(null);

  useEffect(() => {
    return () => {
      if (toastTimerRef.current) clearTimeout(toastTimerRef.current);
      if (captureTimerRef.current) clearTimeout(captureTimerRef.current);
    };
  }, []);

  const showToast = (message, type = 'success') => {
    if (toastTimerRef.current) clearTimeout(toastTimerRef.current);
    setToast({ message, type });
    toastTimerRef.current = setTimeout(() => setToast(null), 3500);
  };

  // 비즈니스 로직 분리
  const modelingHook = useBeamModeling();
  const analysisManager = useAnalysisManager(modelingHook, showToast, setActiveTab);

  const { beamType, params, loads, boundaries, validationErrors } = modelingHook;
  const { dispData, elForceData, stressData, summaryData, hasCharts, isAnalyzing, isReadOnly, globalJob } = analysisManager;

  const handleJsonUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const json = JSON.parse(event.target.result);
        analysisManager.processResultJson(json);
        if (json.result) showToast("모델 및 해석 결과가 성공적으로 로드되었습니다.", "success");
        else showToast("모델 기하정보가 로드되었습니다. (해석 결과는 없음)", "info");
      } catch (error) { 
        showToast("JSON 파싱 오류: 올바른 형식의 파일인지 확인하세요.", "error"); 
      }
    };
    reader.readAsText(file);
    e.target.value = null; 
  };

  const handleCapture = async () => {
    if (!captureRef.current) return;
    setIsCapturing(true);
    captureTimerRef.current = setTimeout(async () => {
      try {
        const dataUrl = await toPng(captureRef.current, { backgroundColor: '#020617', pixelRatio: 2, cacheBust: true });
        const link = document.createElement('a');
        link.download = `HiTess_Full_Report_${new Date().getTime()}.png`;
        link.href = dataUrl;
        link.click();
      } catch (error) {
        showToast("이미지 캡처 중 오류가 발생했습니다.", "error");
      } finally {
        setIsCapturing(false); 
      }
    }, 800); 
  };

  const handleReset = () => {
    analysisManager.resetResults();
    modelingHook.resetModeling();
    setActiveTab('modeling');
  };

  return (
    <>
    <div ref={captureRef} className={isCapturing ? "w-[1200px] bg-slate-950 p-12 flex flex-col gap-8 absolute top-0 left-0 z-[9999]" : "grid grid-cols-[400px_1fr] w-full h-[calc(100vh-100px)] min-h-[600px] bg-slate-950 p-4 gap-4 rounded-2xl shadow-inner overflow-hidden relative"}>
      
      {/* Toast */}
      {toast && (
        <div className={`fixed top-12 left-1/2 -translate-x-1/2 z-[99999] flex items-center gap-4 px-8 py-5 rounded-2xl shadow-[0_20px_50px_-10px_rgba(0,0,0,0.7)] border transition-all animate-fade-in-up backdrop-blur-xl ${
          toast.type === 'success' ? 'bg-emerald-950/95 border-emerald-500/60 text-emerald-400' :
          toast.type === 'error' ? 'bg-red-950/95 border-red-500/60 text-red-400' : 'bg-indigo-950/95 border-indigo-500/60 text-indigo-400'
        }`}>
          {toast.type === 'success' && <ShieldCheck size={28} />}
          {toast.type === 'error' && <Activity size={28} />}
          {toast.type === 'info' && <Info size={28} />}
          <span className="text-base font-bold tracking-wide whitespace-pre-line">{toast.message}</span>
        </div>
      )}

      {isCapturing && (
        <div className="w-full flex justify-between items-end border-b border-slate-800 pb-6 shrink-0">
           <div>
             <h1 className="text-3xl font-bold text-white tracking-widest">STRUCTURAL ANALYSIS REPORT</h1>
             <p className="text-slate-400 mt-2 text-sm">Generated by HiTESS WorkBench • Simple Beam Assessment</p>
           </div>
           <div className="text-right">
             <p className="text-emerald-400 font-mono text-sm">Date: {new Date().toLocaleString()}</p>
             <p className="text-slate-400 font-mono text-sm mt-1">Beam Type: {beamType} | Length: {params.length}mm</p>
           </div>
        </div>
      )}

      {/* --- Left Panel (Modeling & Controls) --- */}
      {!isCapturing && (
        <div className="flex flex-col h-full overflow-hidden bg-slate-900 rounded-xl border border-slate-800 shadow-2xl relative z-10">
          <div className="flex items-center border-b border-slate-800 bg-slate-800/80 sticky top-0 z-20 backdrop-blur-md">
            <button onClick={() => setActiveTab('modeling')} className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer ${activeTab === 'modeling' ? 'text-[#00E600] border-b-2 border-[#00E600] bg-slate-800' : 'text-slate-400 hover:text-white'}`}>
              <SlidersHorizontal size={14} className="inline mr-2 mb-0.5"/> Modeling
            </button>
            <button onClick={() => setActiveTab('results')} className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer ${activeTab === 'results' ? 'text-[#00E600] border-b-2 border-[#00E600] bg-slate-800' : 'text-slate-400 hover:text-white'}`}>
              <BarChart2 size={14} className="inline mr-2 mb-0.5"/> Analysis Results
            </button>
            <div className="px-2">
              <GuideButton guideTitle="[대화형] Simple Beam Assessment — 보 해석" />
            </div>
          </div>

          <div className="flex-1 overflow-y-auto custom-scrollbar relative">
            {isReadOnly && activeTab === 'modeling' && (
              <div className="absolute inset-0 bg-slate-900/60 z-10 pointer-events-none rounded-xl backdrop-blur-[1px] flex flex-col items-center pt-20">
                 <div className="bg-slate-800 border border-slate-700 px-4 py-2 rounded-lg text-emerald-400 text-xs font-bold shadow-xl">
                   {isAnalyzing ? "⏳ 서버에서 해석을 수행 중입니다..." : "🔒 해석 결과 적용 중 (입력 수정 불가)"}
                 </div>
              </div>
            )}

            {activeTab === 'modeling' && (
              <div className="p-5 space-y-6">
                <div className="flex justify-between items-center bg-indigo-900/20 p-3 rounded-lg border border-indigo-500/30">
                  <span className="text-[11px] font-medium text-indigo-300">Import Model or result.json</span>
                  <label className={`cursor-pointer bg-indigo-600 text-white text-xs px-3 py-1.5 rounded flex items-center gap-1 font-bold shadow-md transition-colors ${isReadOnly ? 'opacity-50 cursor-not-allowed' : 'hover:bg-indigo-500'}`}>
                    <FileJson size={14}/> Load JSON
                    <input type="file" accept=".json" className="hidden" disabled={isReadOnly} onChange={handleJsonUpload} />
                  </label>
                </div>

                <section>
                  <div className="flex justify-between items-end mb-4">
                    <h3 className="text-xs font-bold text-[#00E600] uppercase tracking-wider flex items-center gap-2"><Box size={14} /> Cross Section</h3>
                    <div className="w-16 h-16 bg-slate-800 border border-slate-700 rounded-lg p-1 flex items-center justify-center"><SectionGuide type={beamType} /></div>
                  </div>
                  <select disabled={isReadOnly} value={beamType} onChange={(e) => modelingHook.handleBeamTypeChange(e.target.value)} className={`w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white font-bold mb-4 outline-none ${isReadOnly ? 'opacity-50 cursor-not-allowed' : 'focus:border-[#00E600] cursor-pointer'}`}>
                    <option value="I">I-Beam</option><option value="H">H-Beam</option><option value="BAR">BAR (Solid Box)</option><option value="L">L-Beam (Angle)</option><option value="T">T-Beam</option><option value="CHAN">Channel (C-Shape)</option><option value="ROD">ROD (Solid Cylinder)</option><option value="TUBE">TUBE (Hollow Pipe)</option>
                  </select>
                  <div className="space-y-1">
                    <InputRow label="Length (L)" value={params.length} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, length: e.target.value})} />
                    {beamType === 'ROD' && <InputRow label="Diameter (D)" value={params.dim1} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim1: e.target.value})} />}
                    {beamType === 'TUBE' && (<><InputRow label="Outer Dia (D)" value={params.dim1} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim1: e.target.value})} /><InputRow label="Thickness (t)" value={params.dim2} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim2: e.target.value})} /></>)}
                    {['BAR', 'I', 'H', 'L', 'T', 'CHAN'].includes(beamType) && (<><InputRow label="Width (W)" value={params.dim1} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim1: e.target.value})} /><InputRow label="Height (H)" value={params.dim2} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim2: e.target.value})} /></>)}
                    {['I', 'H', 'L', 'T', 'CHAN'].includes(beamType) && (<><InputRow label="Flange Thk (tf)" value={params.dim3} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim3: e.target.value})} /><InputRow label="Web Thk (tw)" value={params.dim4} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim4: e.target.value})} /></>)}
                  </div>
                </section>

                <section className="border-t border-slate-800 pt-6">
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="text-xs font-bold text-[#00E600] uppercase tracking-wider flex items-center gap-2"><ShieldCheck size={14} /> Boundaries</h3>
                    {!isReadOnly && <button onClick={() => modelingHook.setBoundaries([...boundaries, { pos: (Number(params.length)||0)/2, type: 'Hinge', dof: '' }])} className="text-slate-400 hover:text-blue-400 cursor-pointer"><Plus size={16}/></button>}
                  </div>
                  <div className="space-y-2">
                    {boundaries.map((bc, idx) => (
                      <div key={idx} className={`flex gap-1 items-center bg-slate-950 p-1.5 rounded-lg border border-slate-800 ${isReadOnly && 'opacity-60'}`}>
                        <div className="relative flex-1"><input type="number" disabled={isReadOnly} value={bc.pos} onChange={e => modelingHook.updateBc(idx, 'pos', e.target.value)} className="w-full bg-transparent px-2 py-1 text-sm text-white outline-none font-mono text-right pr-8 disabled:cursor-not-allowed" /><span className="absolute right-2 top-1.5 text-[10px] text-slate-500 font-mono">mm</span></div>
                        <select disabled={isReadOnly} value={bc.type} onChange={e => modelingHook.updateBc(idx, 'type', e.target.value)} className="w-[72px] bg-slate-800 rounded px-1 py-1 text-[11px] text-white outline-none disabled:cursor-not-allowed">
                          <option value="Fix">Fix</option><option value="Hinge">Hinge</option><option value="Roller">Roller</option><option value="Custom">Custom</option>
                        </select>
                        {bc.type === 'Custom' && <input type="text" disabled={isReadOnly} placeholder="DOF" value={bc.dof || ''} onChange={e => modelingHook.updateBc(idx, 'dof', e.target.value)} className="w-12 bg-slate-900 border border-slate-700 text-white text-[10px] px-1 rounded outline-none text-center font-mono" />}
                        {!isReadOnly && <button onClick={() => modelingHook.setBoundaries(boundaries.filter((_, i) => i !== idx))} className="p-1 text-slate-500 hover:text-red-400 cursor-pointer"><Trash2 size={14}/></button>}
                      </div>
                    ))}
                  </div>
                </section>

                <section className="border-t border-slate-800 pt-6 mb-6">
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="text-xs font-bold text-[#00E600] uppercase tracking-wider flex items-center gap-2"><ArrowDown size={14} /> Static Loads</h3>
                    {!isReadOnly && <button onClick={() => modelingHook.setLoads([...loads, { pos: (Number(params.length)||0)/2, fx: 0, fy: 0, fz: -5000 }])} className="text-slate-400 hover:text-red-400 cursor-pointer"><Plus size={16}/></button>}
                  </div>
                  <div className="space-y-3">
                    {loads.map((load, idx) => (
                      <div key={idx} className={`flex flex-col gap-1.5 bg-slate-950 p-2 rounded-lg border border-slate-800 ${isReadOnly && 'opacity-60'}`}>
                        <div className="flex gap-2 items-center">
                           <span className="text-[10px] text-slate-400 font-bold uppercase w-8 tracking-wider">POS</span>
                           <div className="relative flex-1">
                             <input type="number" disabled={isReadOnly} value={load.pos} onChange={e => modelingHook.updateLoad(idx, 'pos', e.target.value)} className="w-full bg-slate-900 border border-slate-800 focus:border-red-500 px-2 py-1 text-sm text-white outline-none font-mono text-right pr-6 rounded disabled:cursor-not-allowed" />
                             <span className="absolute right-2 top-1.5 text-[10px] text-slate-500 font-mono">mm</span>
                           </div>
                           {!isReadOnly && <button onClick={() => modelingHook.setLoads(loads.filter((_, i) => i !== idx))} className="p-1 text-slate-500 hover:text-red-400 cursor-pointer"><Trash2 size={14}/></button>}
                        </div>
                        <div className="flex gap-1.5">
                           {['fx', 'fy', 'fz'].map(axis => (
                             <div key={axis} className="relative flex-1 flex items-center border border-slate-800 rounded bg-slate-900 overflow-hidden focus-within:border-red-500">
                                <span className="text-[9px] font-bold text-slate-500 pl-1.5 uppercase">{axis}</span>
                                <input type="number" disabled={isReadOnly} value={load[axis]} onChange={e => modelingHook.updateLoad(idx, axis, e.target.value)} className="w-full bg-transparent px-1 py-1 text-xs text-red-400 outline-none font-mono text-right disabled:cursor-not-allowed" />
                             </div>
                           ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </section>
              </div>
            )}

            {activeTab === 'results' && (
              <div className="p-5 space-y-6 h-full flex flex-col">
                <div className="mb-2 text-slate-300 text-sm"><p>해석이 완료된 <strong>result.json</strong> 파일을 업로드하시면 모델 조건과 해석 결과가 한 번에 적용됩니다.</p></div>
                {!hasCharts ? (
                  <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed border-slate-600 rounded-xl cursor-pointer hover:bg-slate-800 transition-colors">
                    <Upload size={28} className="text-slate-400 mb-3"/>
                    <span className="text-sm font-bold text-emerald-400 mb-1">Upload result.json</span>
                    <span className="text-[11px] text-slate-500">클릭하여 파일 선택</span>
                    <input type="file" accept=".json" className="hidden" onChange={handleJsonUpload} />
                  </label>
                ) : (
                  <div className="space-y-4">
                    <div className="bg-emerald-900/20 border border-emerald-500/30 p-4 rounded-xl">
                      <h4 className="text-sm font-bold text-emerald-400 mb-1 flex items-center gap-2"><Activity size={16}/> 해석 데이터 적용 완료</h4>
                      <p className="text-xs text-emerald-300/70">우측 뷰어에서 3D 변형 형상 및 하단의 응력/단면력 차트를 확인하세요.</p>
                    </div>
                    {summaryData && (
                      <div className="bg-slate-950 rounded-xl border border-slate-800 p-4 mt-2 shadow-lg">
                        <h4 className="text-xs font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-2 mb-3">Analysis Summary</h4>
                        <div className="flex flex-col gap-2.5 text-xs">
                          <SummaryRow label="Total Weight" value={summaryData.totalWeight?.toFixed(2)} unit="kg" />
                          <SummaryRow label="Max Displacement (Z)" value={summaryData.maxDispNode?.dispZ?.toFixed(4)} unit="mm" sub={`@ Node ${summaryData.maxDispNode?.nodeId} (X: ${summaryData.maxDispNode?.x}mm)`} />
                          <SummaryRow label="Max Stress" value={engFormat(summaryData.maxStressElement?.sMax || summaryData.maxStressElement?.maxStress)} unit="MPa" sub={`@ Element ${summaryData.maxStressElement?.elementId}`} />
                          <SummaryRow label="Max Shear Force" value={engFormat(summaryData.maxShearForceElement?.shearForce1)} unit="N" sub={`@ Element ${summaryData.maxShearForceElement?.elementId}`} />
                          <SummaryRow label="Max Bending Moment" value={engFormat(summaryData.maxBendingMomentElement?.bendingMoment1)} unit="N·mm" sub={`@ Element ${summaryData.maxBendingMomentElement?.elementId}`} />
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="p-4 border-t border-slate-800 bg-slate-900 shrink-0 z-20">
             {validationErrors.length > 0 && !isReadOnly && (
                <div className="mb-3 p-2 bg-red-950/50 border border-red-800 rounded text-[11px] text-red-300">
                  <strong className="block mb-1">입력 오류:</strong>{validationErrors.map((err, idx) => <div key={idx}>- {err}</div>)}
                </div>
             )}
            {hasCharts ? (
              <button onClick={handleReset} className="w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all cursor-pointer bg-red-900/30 text-red-400 hover:bg-red-900/50 border border-red-800/50 shadow-lg">
                <Trash2 size={18} /> 데이터 초기화 (Clear Results)
              </button>
            ) : isAnalyzing ? (
              <div className="w-full flex flex-col items-center bg-slate-800 p-3 rounded-xl border border-slate-700 shadow-inner">
                <div className="flex justify-between w-full text-[11px] text-emerald-400 font-bold mb-2">
                  <span className="flex items-center gap-2"><RefreshCw className="animate-spin" size={14}/> {globalJob?.message || "서버 대기 중..."}</span>
                  <span>{globalJob?.progress || 0}%</span>
                </div>
                <div className="w-full bg-slate-900 rounded-full h-2.5 overflow-hidden">
                  <div className="bg-emerald-500 h-2.5 rounded-full transition-all duration-300" style={{ width: `${globalJob?.progress || 0}%` }}></div>
                </div>
              </div>
            ) : (
              <button onClick={analysisManager.handleRunAnalysis} disabled={validationErrors.length > 0} className={`w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all cursor-pointer shadow-lg ${validationErrors.length > 0 ? 'bg-slate-700 text-slate-500 cursor-not-allowed' : 'bg-[#00E600] text-[#002554] hover:shadow-[0_0_20px_rgba(0,230,0,0.4)]'}`}>
                <Play size={18} className="fill-current" /> 서버에서 해석 실행 (Run)
              </button>
            )}
          </div>
        </div>
      )}

      {/* --- Right Panel (Viewers) --- */}
      <div className={`flex flex-col rounded-xl shadow-2xl border border-slate-800 z-0 relative bg-slate-950 transition-all ${isCapturing ? 'w-full h-max gap-8 overflow-visible pb-16' : 'h-full overflow-hidden'}`}>
        {!isCapturing && hasCharts && (
          <button onClick={handleCapture} className="absolute top-4 right-4 z-50 bg-indigo-600/90 hover:bg-indigo-500 p-2.5 rounded-lg border border-indigo-400 text-white transition-colors flex items-center gap-2 shadow-[0_4px_15px_rgba(79,70,229,0.5)] cursor-pointer">
            <Camera size={18}/> <span className="text-xs font-bold tracking-wider">FULL REPORT</span>
          </button>
        )}
        <Viewer3D beamType={beamType} params={params} loads={loads} boundaries={boundaries} dispData={dispData} hasCharts={hasCharts} isCapturing={isCapturing} />
        {hasCharts && <EngineeringCharts dispData={dispData} elForceData={elForceData} stressData={stressData} isCapturing={isCapturing} />}
      </div>
    </div>
    <SolverCredit contributor="권혁민" />
    </>
  );
}