/**
 * @fileoverview Simple Beam Assessment 페이지 오케스트레이터 (BeamModelPreview)
 *  - 하중 입력: N / ton 단위 토글 (해석 제출은 N 으로 정규화)
 *  - 캡쳐: Full Report / Max Displacement / Max Stress 3종, 모두 화이트 테마
 *  - Viewer3D 는 항상 한 인스턴스만 마운트해 캡쳐 시 씬 재생성을 방지한다.
 */
import React, { useState, useRef, useEffect } from 'react';
import { toPng } from 'html-to-image';
import {
  Box, Activity, Plus, Trash2, ShieldCheck, ArrowDown, RefreshCw,
  SlidersHorizontal, Play, FileJson, Upload, BarChart2, Camera,
  Download, ChevronDown, FileText
} from 'lucide-react';
import GuideButton from '../ui/GuideButton';
import { useBeamModeling } from '../../hooks/useBeamModeling';
import { useAnalysisManager } from '../../hooks/useAnalysisManager';
import { InputRow, SummaryRow, SectionGuide } from '../../components/analysis/BeamSharedUI';
import Viewer3D from '../../components/analysis/Viewer3D';
import EngineeringCharts from '../../components/analysis/EngineeringCharts';
import SolverCredit from '../ui/SolverCredit';
import { formatEngineering as engFormat } from '../../utils/formatting';
import { useToast } from '../../contexts/ToastContext';

const CAPTURE_LABEL = {
  full: 'Full Report',
  displacement: 'Max Displacement',
  stress: 'Max Stress',
};

/** 캡쳐 보고서 안의 KPI 타일 (화이트 테마) */
function ReportTile({ label, value, unit, sub, accent = 'emerald' }) {
  const accentMap = {
    emerald: 'text-emerald-700 border-emerald-200 bg-emerald-50',
    sky:     'text-sky-700 border-sky-200 bg-sky-50',
    amber:   'text-amber-700 border-amber-200 bg-amber-50',
    violet:  'text-violet-700 border-violet-200 bg-violet-50',
    rose:    'text-rose-700 border-rose-200 bg-rose-50',
  };
  return (
    <div className={`rounded-xl border ${accentMap[accent]} px-5 py-4 flex flex-col`}>
      <span className="text-[11px] font-bold uppercase tracking-wider opacity-80">{label}</span>
      <span className="mt-1 text-2xl font-black text-slate-900 leading-tight">
        {value} <span className="text-base font-medium opacity-70">{unit}</span>
      </span>
      {sub && <span className="text-[11px] text-slate-500 font-mono mt-1">{sub}</span>}
    </div>
  );
}

/** 캡쳐 보고서 헤더 */
function ReportHeader({ title, beamType, length }) {
  return (
    <div className="w-full flex justify-between items-end border-b-2 border-slate-200 pb-5 shrink-0">
      <div>
        <h1 className="text-3xl font-black text-slate-900 tracking-widest">{title}</h1>
        <p className="text-slate-500 mt-1.5 text-sm">Generated by HiTESS WorkBench • Simple Beam Assessment</p>
      </div>
      <div className="text-right">
        <p className="text-emerald-600 font-mono text-sm font-bold">{new Date().toLocaleString()}</p>
        <p className="text-slate-500 font-mono text-xs mt-1">Beam Type: {beamType} | Length: {length}mm</p>
      </div>
    </div>
  );
}

/** 모델/해석 요약을 두 열로 표시 (full 모드 전용) */
function ModelAnalysisGrid({ beamType, params, boundaries, loads, summaryData }) {
  const dimsLabel = (() => {
    const { dim1, dim2, dim3, dim4 } = params;
    if (beamType === 'ROD') return `D=${dim1}mm`;
    if (beamType === 'TUBE') return `D=${dim1}mm, t=${dim2}mm`;
    if (['BAR'].includes(beamType)) return `${dim1}×${dim2}mm`;
    return `${dim1}×${dim2}×${dim3}×${dim4}mm`;
  })();

  return (
    <div className="grid grid-cols-2 gap-5 w-full">
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-5">
        <h3 className="text-xs font-black text-slate-700 uppercase tracking-wider mb-3 flex items-center gap-2">
          <Box size={14} /> Model Configuration
        </h3>
        <div className="space-y-1.5 text-xs">
          <div className="flex justify-between border-b border-slate-200 pb-1.5"><span className="text-slate-500">Section Type</span><span className="font-bold text-slate-800 font-mono">{beamType}</span></div>
          <div className="flex justify-between border-b border-slate-200 pb-1.5"><span className="text-slate-500">Length</span><span className="font-bold text-slate-800 font-mono">{params.length} mm</span></div>
          <div className="flex justify-between border-b border-slate-200 pb-1.5"><span className="text-slate-500">Section Dims</span><span className="font-bold text-slate-800 font-mono text-right">{dimsLabel}</span></div>
          <div className="flex justify-between border-b border-slate-200 pb-1.5">
            <span className="text-slate-500">Boundaries</span>
            <span className="font-bold text-slate-800 font-mono text-right text-[11px]">
              {boundaries.map(b => `${b.type}@${b.pos}mm`).join(', ') || '-'}
            </span>
          </div>
          <div className="flex flex-col">
            <span className="text-slate-500 mb-1">Loads</span>
            <div className="space-y-0.5">
              {loads.map((l, i) => {
                const u = l.unit || 'N';
                return (
                  <div key={i} className="font-mono text-[10.5px] text-slate-700 bg-white border border-slate-200 rounded px-2 py-1">
                    [{i+1}] @ {l.pos}mm — fx={l.fx}{u}, fy={l.fy}{u}, fz={l.fz}{u}
                  </div>
                );
              })}
              {loads.length === 0 && <span className="text-slate-400 font-mono">-</span>}
            </div>
          </div>
        </div>
      </div>

      <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-5">
        <h3 className="text-xs font-black text-emerald-700 uppercase tracking-wider mb-3 flex items-center gap-2">
          <Activity size={14} /> Analysis Summary
        </h3>
        <div className="space-y-1.5 text-xs">
          <div className="flex justify-between border-b border-emerald-200 pb-1.5"><span className="text-slate-500">Total Weight</span><span className="font-bold text-slate-800 font-mono">{summaryData?.totalWeight?.toFixed(2) || '-'} kg</span></div>
          <div className="flex justify-between border-b border-emerald-200 pb-1.5">
            <span className="text-slate-500">Max Disp Z</span>
            <span className="font-bold text-slate-800 font-mono text-right">
              {summaryData?.maxDispNode?.dispZ?.toFixed(2) || '-'} mm
              {summaryData?.maxDispNode?.x != null && <span className="text-slate-400 ml-1">@ X={summaryData.maxDispNode.x}</span>}
            </span>
          </div>
          <div className="flex justify-between border-b border-emerald-200 pb-1.5">
            <span className="text-slate-500">Max Stress</span>
            <span className="font-bold text-slate-800 font-mono text-right">
              {engFormat(summaryData?.maxStressElement?.sMax || summaryData?.maxStressElement?.maxStress)} MPa
              {summaryData?.maxStressElement?.elementId != null && <span className="text-slate-400 ml-1">@ Elem {summaryData.maxStressElement.elementId}</span>}
            </span>
          </div>
          <div className="flex justify-between border-b border-emerald-200 pb-1.5">
            <span className="text-slate-500">Max Shear Force</span>
            <span className="font-bold text-slate-800 font-mono text-right">
              {engFormat(summaryData?.maxShearForceElement?.shearForce1)} N
              {summaryData?.maxShearForceElement?.elementId != null && <span className="text-slate-400 ml-1">@ Elem {summaryData.maxShearForceElement.elementId}</span>}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-slate-500">Max Bending Moment</span>
            <span className="font-bold text-slate-800 font-mono text-right">
              {engFormat(summaryData?.maxBendingMomentElement?.bendingMoment1)} N·mm
              {summaryData?.maxBendingMomentElement?.elementId != null && <span className="text-slate-400 ml-1">@ Elem {summaryData.maxBendingMomentElement.elementId}</span>}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

/** 모드별 KPI 타일 묶음 */
function KpiSection({ mode, summaryData, beamType, params }) {
  if (mode === 'full') {
    return (
      <div className="grid grid-cols-4 gap-4 w-full">
        <ReportTile label="Max Disp Z" value={summaryData?.maxDispNode?.dispZ?.toFixed(2) || '-'} unit="mm"
          sub={summaryData?.maxDispNode?.x != null ? `@ X = ${summaryData.maxDispNode.x} mm` : ''} accent="sky" />
        <ReportTile label="Max Stress" value={engFormat(summaryData?.maxStressElement?.sMax || summaryData?.maxStressElement?.maxStress)} unit="MPa"
          sub={summaryData?.maxStressElement?.elementId != null ? `@ Element ${summaryData.maxStressElement.elementId}` : ''} accent="violet" />
        <ReportTile label="Max Shear" value={engFormat(summaryData?.maxShearForceElement?.shearForce1)} unit="N"
          sub={summaryData?.maxShearForceElement?.elementId != null ? `@ Element ${summaryData.maxShearForceElement.elementId}` : ''} accent="amber" />
        <ReportTile label="Max Moment" value={engFormat(summaryData?.maxBendingMomentElement?.bendingMoment1)} unit="N·mm"
          sub={summaryData?.maxBendingMomentElement?.elementId != null ? `@ Element ${summaryData.maxBendingMomentElement.elementId}` : ''} accent="rose" />
      </div>
    );
  }
  if (mode === 'displacement') {
    return (
      <div className="grid grid-cols-2 gap-4 w-full">
        <ReportTile label="Max Disp Z" value={summaryData?.maxDispNode?.dispZ?.toFixed(2) || '-'} unit="mm"
          sub={summaryData?.maxDispNode?.x != null ? `@ X = ${summaryData.maxDispNode.x} mm (Node ${summaryData.maxDispNode.nodeId})` : ''} accent="sky" />
        <ReportTile label="Total Weight" value={summaryData?.totalWeight?.toFixed(2) || '-'} unit="kg"
          sub={`Beam ${beamType} • L = ${params.length} mm`} accent="emerald" />
      </div>
    );
  }
  if (mode === 'stress') {
    return (
      <div className="grid grid-cols-2 gap-4 w-full">
        <ReportTile label="Max Stress" value={engFormat(summaryData?.maxStressElement?.sMax || summaryData?.maxStressElement?.maxStress)} unit="MPa"
          sub={summaryData?.maxStressElement?.elementId != null ? `@ Element ${summaryData.maxStressElement.elementId}` : ''} accent="violet" />
        <ReportTile label="Max Bending Moment" value={engFormat(summaryData?.maxBendingMomentElement?.bendingMoment1)} unit="N·mm"
          sub={summaryData?.maxBendingMomentElement?.elementId != null ? `@ Element ${summaryData.maxBendingMomentElement.elementId}` : ''} accent="rose" />
      </div>
    );
  }
  return null;
}

export default function BeamModelPreview() {
  const { showToast } = useToast();
  const captureRef = useRef(null);
  const captureTimerRef = useRef(null);
  const captureMenuRef = useRef(null);
  const [activeTab, setActiveTab] = useState('modeling');
  const [captureMode, setCaptureMode] = useState(null); // null | 'full' | 'displacement' | 'stress'
  const [showCaptureMenu, setShowCaptureMenu] = useState(false);
  const isCapturing = !!captureMode;

  useEffect(() => {
    return () => {
      if (captureTimerRef.current) clearTimeout(captureTimerRef.current);
    };
  }, []);

  // 드롭다운 외부 클릭 시 닫기
  useEffect(() => {
    if (!showCaptureMenu) return;
    const onDocClick = (e) => {
      if (captureMenuRef.current && !captureMenuRef.current.contains(e.target)) {
        setShowCaptureMenu(false);
      }
    };
    document.addEventListener('mousedown', onDocClick);
    return () => document.removeEventListener('mousedown', onDocClick);
  }, [showCaptureMenu]);

  const modelingHook = useBeamModeling();
  const analysisManager = useAnalysisManager(modelingHook, showToast, setActiveTab);

  const { beamType, params, loads, boundaries, validationErrors } = modelingHook;
  const { dispData, elForceData, stressData, summaryData, hasCharts, isAnalyzing, isReadOnly, globalJob } = analysisManager;

  const handleJsonUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const json = JSON.parse(event.target.result);
        analysisManager.processResultJson(json);
        if (json.result) showToast("모델 및 해석 결과가 성공적으로 로드되었습니다.", "success");
        else showToast("모델 기하정보가 로드되었습니다. (해석 결과는 없음)", "info");
      } catch (error) {
        showToast("JSON 파싱 오류: 올바른 형식의 파일인지 확인하세요.", "error");
      }
    };
    reader.readAsText(file);
    e.target.value = null;
  };

  const handleCapture = (mode) => {
    if (!captureRef.current) return;
    setShowCaptureMenu(false);
    setCaptureMode(mode);
    captureTimerRef.current = setTimeout(async () => {
      try {
        const dataUrl = await toPng(captureRef.current, { backgroundColor: '#ffffff', pixelRatio: 2, cacheBust: true });
        const link = document.createElement('a');
        const tag = mode === 'full' ? 'FullReport' : mode === 'displacement' ? 'MaxDisplacement' : 'MaxStress';
        link.download = `HiTess_${tag}_${new Date().getTime()}.png`;
        link.href = dataUrl;
        link.click();
        showToast(`${CAPTURE_LABEL[mode]} 이미지를 저장했습니다.`, 'success');
      } catch (error) {
        showToast("이미지 캡처 중 오류가 발생했습니다.", "error");
      } finally {
        setCaptureMode(null);
      }
    }, 800);
  };

  const handleReset = () => {
    analysisManager.resetResults();
    modelingHook.resetModeling();
    setActiveTab('modeling');
  };

  // 캡쳐 모드별 표시 결정
  const showHeader = isCapturing;
  const showLeft = !isCapturing;
  const showCaptureKpi = isCapturing;
  const show3D = !isCapturing || captureMode !== 'stress';
  const showModelAnalysis = isCapturing && captureMode === 'full';
  const showFooter = isCapturing;

  // 캡쳐 모드 상세 타이틀
  const reportTitle =
    captureMode === 'full' ? 'STRUCTURAL ANALYSIS REPORT' :
    captureMode === 'displacement' ? 'MAX DISPLACEMENT REPORT' :
    captureMode === 'stress' ? 'MAX STRESS REPORT' : '';

  return (
    <>
    <div
      ref={captureRef}
      className={
        isCapturing
          ? "w-[1200px] bg-white p-12 flex flex-col gap-6 absolute top-0 left-0 z-[9999]"
          : "grid grid-cols-[400px_1fr] w-full h-[calc(100vh-100px)] min-h-[600px] bg-slate-950 p-4 gap-4 rounded-2xl shadow-inner overflow-hidden relative"
      }
    >
      {/* ───── 캡쳐 모드 헤더 ───── */}
      {showHeader && <ReportHeader title={reportTitle} beamType={beamType} length={params.length} />}

      {/* ───── 좌측 모델링 패널 (캡쳐 시 숨김) ───── */}
      {showLeft && (
        <div className="flex flex-col h-full overflow-hidden bg-slate-900 rounded-xl border border-slate-800 shadow-2xl relative z-10">
          <div className="flex items-center border-b border-slate-800 bg-slate-800/80 sticky top-0 z-20 backdrop-blur-md">
            <button onClick={() => setActiveTab('modeling')} className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer ${activeTab === 'modeling' ? 'text-brand-accent border-b-2 border-brand-accent bg-slate-800' : 'text-slate-400 hover:text-white'}`}>
              <SlidersHorizontal size={14} className="inline mr-2 mb-0.5"/> Modeling
            </button>
            <button onClick={() => setActiveTab('results')} className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider transition-colors cursor-pointer ${activeTab === 'results' ? 'text-brand-accent border-b-2 border-brand-accent bg-slate-800' : 'text-slate-400 hover:text-white'}`}>
              <BarChart2 size={14} className="inline mr-2 mb-0.5"/> Analysis Results
            </button>
            <div className="px-2">
              <GuideButton guideTitle="[대화형] Simple Beam Assessment — 보 해석" />
            </div>
          </div>

          <div className="flex-1 overflow-y-auto custom-scrollbar relative">
            {isReadOnly && activeTab === 'modeling' && (
              <div className="absolute inset-0 bg-slate-900/60 z-10 pointer-events-none rounded-xl backdrop-blur-[1px] flex flex-col items-center pt-20">
                 <div className="bg-slate-800 border border-slate-700 px-4 py-2 rounded-lg text-emerald-400 text-xs font-bold shadow-xl">
                   {isAnalyzing ? "⏳ 서버에서 해석을 수행 중입니다..." : "🔒 해석 결과 적용 중 (입력 수정 불가)"}
                 </div>
              </div>
            )}

            {activeTab === 'modeling' && (
              <div className="p-5 space-y-6">
                <div className="flex justify-between items-center bg-indigo-900/20 p-3 rounded-lg border border-indigo-500/30">
                  <span className="text-[11px] font-medium text-indigo-300">Import Model or result.json</span>
                  <label className={`cursor-pointer bg-indigo-600 text-white text-xs px-3 py-1.5 rounded flex items-center gap-1 font-bold shadow-md transition-colors ${isReadOnly ? 'opacity-50 cursor-not-allowed' : 'hover:bg-indigo-500'}`}>
                    <FileJson size={14}/> Load JSON
                    <input type="file" accept=".json" className="hidden" disabled={isReadOnly} onChange={handleJsonUpload} />
                  </label>
                </div>

                <section>
                  <div className="flex justify-between items-end mb-4">
                    <h3 className="text-xs font-bold text-brand-accent uppercase tracking-wider flex items-center gap-2"><Box size={14} /> Cross Section</h3>
                    <div className="w-16 h-16 bg-slate-800 border border-slate-700 rounded-lg p-1 flex items-center justify-center"><SectionGuide type={beamType} /></div>
                  </div>
                  <select disabled={isReadOnly} value={beamType} onChange={(e) => modelingHook.handleBeamTypeChange(e.target.value)} className={`w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white font-bold mb-4 outline-none ${isReadOnly ? 'opacity-50 cursor-not-allowed' : 'focus:border-brand-accent cursor-pointer'}`}>
                    <option value="I">I-Beam</option><option value="H">H-Beam</option><option value="BAR">BAR (Solid Box)</option><option value="L">L-Beam (Angle)</option><option value="T">T-Beam</option><option value="CHAN">Channel (C-Shape)</option><option value="ROD">ROD (Solid Cylinder)</option><option value="TUBE">TUBE (Hollow Pipe)</option>
                  </select>
                  <div className="space-y-1">
                    <InputRow label="Length (L)" value={params.length} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, length: e.target.value})} />
                    {beamType === 'ROD' && <InputRow label="Diameter (D)" value={params.dim1} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim1: e.target.value})} />}
                    {beamType === 'TUBE' && (<><InputRow label="Outer Dia (D)" value={params.dim1} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim1: e.target.value})} /><InputRow label="Thickness (t)" value={params.dim2} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim2: e.target.value})} /></>)}
                    {['BAR', 'I', 'H', 'L', 'T', 'CHAN'].includes(beamType) && (<><InputRow label="Width (W)" value={params.dim1} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim1: e.target.value})} /><InputRow label="Height (H)" value={params.dim2} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim2: e.target.value})} /></>)}
                    {['I', 'H', 'L', 'T', 'CHAN'].includes(beamType) && (<><InputRow label="Flange Thk (tf)" value={params.dim3} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim3: e.target.value})} /><InputRow label="Web Thk (tw)" value={params.dim4} unit="mm" disabled={isReadOnly} onChange={(e) => modelingHook.setParams({...params, dim4: e.target.value})} /></>)}
                  </div>
                </section>

                <section className="border-t border-slate-800 pt-6">
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="text-xs font-bold text-brand-accent uppercase tracking-wider flex items-center gap-2"><ShieldCheck size={14} /> Boundaries</h3>
                    {!isReadOnly && <button onClick={() => modelingHook.setBoundaries([...boundaries, { pos: (Number(params.length)||0)/2, type: 'Hinge', dof: '' }])} className="text-slate-400 hover:text-blue-400 cursor-pointer"><Plus size={16}/></button>}
                  </div>
                  <div className="space-y-2">
                    {boundaries.map((bc, idx) => (
                      <div key={idx} className={`flex gap-1 items-center bg-slate-950 p-1.5 rounded-lg border border-slate-800 ${isReadOnly && 'opacity-60'}`}>
                        <div className="relative flex-1"><input type="number" disabled={isReadOnly} value={bc.pos} onChange={e => modelingHook.updateBc(idx, 'pos', e.target.value)} className="w-full bg-transparent px-2 py-1 text-sm text-white outline-none font-mono text-right pr-8 disabled:cursor-not-allowed" /><span className="absolute right-2 top-1.5 text-[10px] text-slate-500 font-mono">mm</span></div>
                        <select disabled={isReadOnly} value={bc.type} onChange={e => modelingHook.updateBc(idx, 'type', e.target.value)} className="w-[72px] bg-slate-800 rounded px-1 py-1 text-[11px] text-white outline-none disabled:cursor-not-allowed">
                          <option value="Fix">Fix</option><option value="Hinge">Hinge</option><option value="Roller">Roller</option><option value="Custom">Custom</option>
                        </select>
                        {bc.type === 'Custom' && <input type="text" disabled={isReadOnly} placeholder="DOF" value={bc.dof || ''} onChange={e => modelingHook.updateBc(idx, 'dof', e.target.value)} className="w-12 bg-slate-900 border border-slate-700 text-white text-[10px] px-1 rounded outline-none text-center font-mono" />}
                        {!isReadOnly && <button onClick={() => modelingHook.setBoundaries(boundaries.filter((_, i) => i !== idx))} className="p-1 text-slate-500 hover:text-red-400 cursor-pointer"><Trash2 size={14}/></button>}
                      </div>
                    ))}
                  </div>
                </section>

                <section className="border-t border-slate-800 pt-6 mb-6">
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="text-xs font-bold text-brand-accent uppercase tracking-wider flex items-center gap-2"><ArrowDown size={14} /> Static Loads</h3>
                    {!isReadOnly && <button onClick={() => modelingHook.setLoads([...loads, { pos: (Number(params.length)||0)/2, fx: 0, fy: 0, fz: -5000, unit: 'N' }])} className="text-slate-400 hover:text-red-400 cursor-pointer"><Plus size={16}/></button>}
                  </div>
                  <div className="space-y-3">
                    {loads.map((load, idx) => {
                      const u = load.unit || 'N';
                      return (
                        <div key={idx} className={`flex flex-col gap-1.5 bg-slate-950 p-2 rounded-lg border border-slate-800 ${isReadOnly && 'opacity-60'}`}>
                          <div className="flex gap-2 items-center">
                             <span className="text-[10px] text-slate-400 font-bold uppercase w-8 tracking-wider">POS</span>
                             <div className="relative flex-1">
                               <input type="number" disabled={isReadOnly} value={load.pos} onChange={e => modelingHook.updateLoad(idx, 'pos', e.target.value)} className="w-full bg-slate-900 border border-slate-800 focus:border-red-500 px-2 py-1 text-sm text-white outline-none font-mono text-right pr-6 rounded disabled:cursor-not-allowed" />
                               <span className="absolute right-2 top-1.5 text-[10px] text-slate-500 font-mono">mm</span>
                             </div>
                             {/* N / ton 단위 토글 — 누르면 fx/fy/fz 가 동등한 힘으로 자동 환산 */}
                             <div className={`flex gap-0.5 bg-slate-800 rounded-md p-0.5 text-[10px] font-bold ${isReadOnly ? 'opacity-50' : ''}`}>
                               <button
                                 type="button"
                                 disabled={isReadOnly}
                                 onClick={() => modelingHook.updateLoadUnit(idx, 'N')}
                                 className={`px-2 py-0.5 rounded transition cursor-pointer ${u === 'N' ? 'bg-emerald-600 text-white shadow' : 'text-slate-400 hover:text-white'}`}
                                 title="Newton 단위로 입력"
                               >N</button>
                               <button
                                 type="button"
                                 disabled={isReadOnly}
                                 onClick={() => modelingHook.updateLoadUnit(idx, 'ton')}
                                 className={`px-2 py-0.5 rounded transition cursor-pointer ${u === 'ton' ? 'bg-emerald-600 text-white shadow' : 'text-slate-400 hover:text-white'}`}
                                 title="Metric ton-force (1 ton = 9806.65 N) — 해석 시 N 으로 환산"
                               >ton</button>
                             </div>
                             {!isReadOnly && <button onClick={() => modelingHook.setLoads(loads.filter((_, i) => i !== idx))} className="p-1 text-slate-500 hover:text-red-400 cursor-pointer"><Trash2 size={14}/></button>}
                          </div>
                          <div className="flex gap-1.5">
                             {['fx', 'fy', 'fz'].map(axis => (
                               <div key={axis} className="relative flex-1 flex items-center border border-slate-800 rounded bg-slate-900 overflow-hidden focus-within:border-red-500">
                                  <span className="text-[9px] font-bold text-slate-500 pl-1.5 uppercase">{axis}</span>
                                  <input type="number" disabled={isReadOnly} value={load[axis]} onChange={e => modelingHook.updateLoad(idx, axis, e.target.value)} className="w-full bg-transparent px-1 py-1 text-xs text-red-400 outline-none font-mono text-right disabled:cursor-not-allowed" />
                                  <span className="text-[9px] text-slate-600 pr-1.5 font-mono">{u}</span>
                               </div>
                             ))}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </section>
              </div>
            )}

            {activeTab === 'results' && (
              <div className="p-5 space-y-6 h-full flex flex-col">
                <div className="mb-2 text-slate-300 text-sm"><p>해석이 완료된 <strong>result.json</strong> 파일을 업로드하시면 모델 조건과 해석 결과가 한 번에 적용됩니다.</p></div>
                {!hasCharts ? (
                  <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed border-slate-600 rounded-xl cursor-pointer hover:bg-slate-800 transition-colors">
                    <Upload size={28} className="text-slate-400 mb-3"/>
                    <span className="text-sm font-bold text-emerald-400 mb-1">Upload result.json</span>
                    <span className="text-[11px] text-slate-500">클릭하여 파일 선택</span>
                    <input type="file" accept=".json" className="hidden" onChange={handleJsonUpload} />
                  </label>
                ) : (
                  <div className="space-y-4">
                    <div className="bg-emerald-900/20 border border-emerald-500/30 p-4 rounded-xl">
                      <h4 className="text-sm font-bold text-emerald-400 mb-1 flex items-center gap-2"><Activity size={16}/> 해석 데이터 적용 완료</h4>
                      <p className="text-xs text-emerald-300/70">우측 뷰어에서 3D 변형 형상 및 하단의 응력/단면력 차트를 확인하세요.</p>
                    </div>
                    {summaryData && (
                      <div className="bg-slate-950 rounded-xl border border-slate-800 p-4 mt-2 shadow-lg">
                        <h4 className="text-xs font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-2 mb-3">Analysis Summary</h4>
                        <div className="flex flex-col gap-2.5 text-xs">
                          <SummaryRow label="Total Weight" value={summaryData.totalWeight?.toFixed(2)} unit="kg" />
                          <SummaryRow label="Max Displacement (Z)" value={summaryData.maxDispNode?.dispZ?.toFixed(2)} unit="mm" sub={`@ Node ${summaryData.maxDispNode?.nodeId} (X: ${summaryData.maxDispNode?.x}mm)`} />
                          <SummaryRow label="Max Stress" value={engFormat(summaryData.maxStressElement?.sMax || summaryData.maxStressElement?.maxStress)} unit="MPa" sub={`@ Element ${summaryData.maxStressElement?.elementId}`} />
                          <SummaryRow label="Max Shear Force" value={engFormat(summaryData.maxShearForceElement?.shearForce1)} unit="N" sub={`@ Element ${summaryData.maxShearForceElement?.elementId}`} />
                          <SummaryRow label="Max Bending Moment" value={engFormat(summaryData.maxBendingMomentElement?.bendingMoment1)} unit="N·mm" sub={`@ Element ${summaryData.maxBendingMomentElement?.elementId}`} />
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="p-4 border-t border-slate-800 bg-slate-900 shrink-0 z-20">
             {validationErrors.length > 0 && !isReadOnly && (
                <div className="mb-3 p-2 bg-red-950/50 border border-red-800 rounded text-[11px] text-red-300">
                  <strong className="block mb-1">입력 오류:</strong>{validationErrors.map((err, idx) => <div key={idx}>- {err}</div>)}
                </div>
             )}
            {hasCharts ? (
              <button onClick={handleReset} className="w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all cursor-pointer bg-red-900/30 text-red-400 hover:bg-red-900/50 border border-red-800/50 shadow-lg">
                <Trash2 size={18} /> 데이터 초기화 (Clear Results)
              </button>
            ) : isAnalyzing ? (
              <div className="w-full flex flex-col items-center bg-slate-800 p-3 rounded-xl border border-slate-700 shadow-inner">
                <div className="flex justify-between w-full text-[11px] text-emerald-400 font-bold mb-2">
                  <span className="flex items-center gap-2"><RefreshCw className="animate-spin" size={14}/> {globalJob?.message || "서버 대기 중..."}</span>
                  <span>{globalJob?.progress || 0}%</span>
                </div>
                <div className="w-full bg-slate-900 rounded-full h-2.5 overflow-hidden">
                  <div className="bg-emerald-500 h-2.5 rounded-full transition-all duration-300" style={{ width: `${globalJob?.progress || 0}%` }}></div>
                </div>
              </div>
            ) : (
              <button onClick={analysisManager.handleRunAnalysis} disabled={validationErrors.length > 0} className={`w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all cursor-pointer shadow-lg ${validationErrors.length > 0 ? 'bg-slate-700 text-slate-500 cursor-not-allowed' : 'bg-brand-accent text-brand-blue hover:shadow-[0_0_20px_rgba(0,230,0,0.4)]'}`}>
                <Play size={18} className="fill-current" /> 서버에서 해석 실행 (Run)
              </button>
            )}
          </div>
        </div>
      )}

      {/* ───── 우측 뷰어 패널 (캡쳐 시 풀 폭으로 확장) ───── */}
      <div
        className={
          isCapturing
            ? "flex flex-col w-full h-max gap-6 overflow-visible"
            : "flex flex-col rounded-xl shadow-2xl border border-slate-800 z-0 relative bg-slate-950 transition-all h-full overflow-hidden"
        }
      >
        {/* 캡쳐 버튼 — 일반 모드에서만 표시 */}
        {!isCapturing && hasCharts && (
          <div className="absolute top-4 right-4 z-50 flex items-center gap-2" ref={captureMenuRef}>
            <button
              onClick={() => handleCapture('full')}
              className="bg-indigo-600/90 hover:bg-indigo-500 px-3 py-2 rounded-lg border border-indigo-400 text-white transition-colors flex items-center gap-2 shadow-[0_4px_15px_rgba(79,70,229,0.5)] cursor-pointer"
              title="3D 뷰 + 4개 차트 + 모델/해석 요약 — 화이트 테마 보고서 1장"
            >
              <Camera size={18}/> <span className="text-xs font-bold tracking-wider">FULL REPORT</span>
            </button>
            <div className="relative">
              <button
                onClick={() => setShowCaptureMenu(v => !v)}
                className="bg-slate-800/90 hover:bg-slate-700 px-3 py-2 rounded-lg border border-slate-600 text-white transition-colors flex items-center gap-1.5 shadow-lg cursor-pointer"
                title="개별 차트 다운로드"
              >
                <Download size={16}/>
                <ChevronDown size={14}/>
              </button>
              {showCaptureMenu && (
                <div className="absolute right-0 top-full mt-2 bg-slate-900 border border-slate-700 rounded-lg shadow-2xl overflow-hidden min-w-[220px] z-50">
                  <button
                    onClick={() => handleCapture('displacement')}
                    className="w-full px-4 py-3 text-left text-xs font-bold text-sky-400 hover:bg-slate-800 flex items-center gap-2 cursor-pointer border-b border-slate-800"
                  >
                    <FileText size={14}/> Max Displacement 보고서
                  </button>
                  <button
                    onClick={() => handleCapture('stress')}
                    className="w-full px-4 py-3 text-left text-xs font-bold text-violet-400 hover:bg-slate-800 flex items-center gap-2 cursor-pointer"
                  >
                    <FileText size={14}/> Max Stress 보고서
                  </button>
                </div>
              )}
            </div>
          </div>
        )}

        {/* 캡쳐 KPI 타일 */}
        {showCaptureKpi && <KpiSection mode={captureMode} summaryData={summaryData} beamType={beamType} params={params} />}

        {/*
          3D 뷰어 — 항상 마운트하여 THREE.js 씬 재생성을 막는다.
          - 일반 모드: wrapper 는 레이아웃 투명(`contents`) — Viewer3D 가 자체 높이(hasCharts 시 45%, 아니면 full)를 직접 제어.
          - 캡쳐 풀/변위 모드: 화이트 테마 카드 프레임 부여.
          - 캡쳐 응력 모드: hidden (3D 컬러는 변위 기반이므로 응력 단독 보고서에선 숨김).
        */}
        <div className={
          show3D
            ? (isCapturing ? 'w-full rounded-xl overflow-hidden border border-slate-200 shadow-sm' : 'contents')
            : 'hidden'
        }>
          <Viewer3D beamType={beamType} params={params} loads={loads} boundaries={boundaries} dispData={dispData} hasCharts={hasCharts} isCapturing={isCapturing} />
        </div>

        {/* 모델/해석 요약 (full 캡쳐 전용) */}
        {showModelAnalysis && <ModelAnalysisGrid beamType={beamType} params={params} boundaries={boundaries} loads={loads} summaryData={summaryData} />}

        {/* 차트 영역 */}
        {hasCharts && <EngineeringCharts dispData={dispData} elForceData={elForceData} stressData={stressData} isCapturing={isCapturing} captureMode={captureMode} />}

        {/* 캡쳐 푸터 */}
        {showFooter && (
          <p className="text-[10px] text-slate-400 font-mono text-right pt-2 border-t border-slate-200">
            © HiTESS WorkBench — Simple Beam Assessment Solver
          </p>
        )}
      </div>
    </div>
    <SolverCredit contributor="권혁민" />
    </>
  );
}
